name: flask-backend-hospital CI CD

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ec2:
    run-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@latest
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        cd /flask-backend-hospital
        git pull

        docker-compose down
        docker-compose up -d