version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # web:
  #   build: .
  #   command: gunicorn -b 0.0.0.0:5000 app:app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=${FLASK_ENV}
  #     - DATABASE_URI=${DATABASE_URI}
  #     - MAIL_SERVER=${MAIL_SERVER}
  #     - MAIL_PORT=${MAIL_PORT}
  #     - MAIL_USE_TLS=${MAIL_USE_TLS}
  #     - MAIL_USE_SSL=${MAIL_USE_SSL}
  #     - MAIL_USERNAME=${MAIL_USERNAME}
  #     - MAIL_PASSWORD=${MAIL_PASSWORD}
  #     - SECRET_KEY=${SECRET_KEY}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - PMA_HOST=${PMA_HOST}
  #     - PMA_USER=${PMA_USER}
  #     - PMA_PASSWORD=${PMA_PASSWORD}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

volumes:
  db_data:
