"""Fix progression data migration.

Revision ID: 187030bad1c2
Revises: 3e0e64fab989
Create Date: 2024-12-13 13:03:15.009849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '187030bad1c2'
down_revision = '3e0e64fab989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_progression_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('document_progression_data', sa.JSON(), nullable=True))
        batch_op.drop_column('progression_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progression_data', mysql.JSON(), nullable=True))
        batch_op.drop_column('document_progression_data')
        batch_op.drop_column('video_progression_data')

    # ### end Alembic commands ###
