"""add push token to patient

Revision ID: 195559357f09
Revises: b57cdbbf2208
Create Date: 2025-01-23 21:50:39.422504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '195559357f09'
down_revision = 'b57cdbbf2208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('push_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('push_token')

    # ### end Alembic commands ###
