"""Update to JSON migration.

Revision ID: 3e0e64fab989
Revises: f76b9588e2f1
Create Date: 2024-12-12 19:32:21.195364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e0e64fab989'
down_revision = 'f76b9588e2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('survey_data',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('progression_data',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('progression_data',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.alter_column('survey_data',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###
