"""change Symptom data type

Revision ID: 45e2472c24f4
Revises: 2c21679c4041
Create Date: 2025-01-10 15:42:03.948478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45e2472c24f4'
down_revision = '2c21679c4041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_symptom_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_data', sa.JSON(), nullable=True))
        batch_op.drop_column('symptom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_symptom_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('survey_data')

    # ### end Alembic commands ###
