"""Update JSON to string  migration.

Revision ID: f76b9588e2f1
Revises: 4e2a85a70701
Create Date: 2024-12-12 18:54:25.598785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f76b9588e2f1'
down_revision = '4e2a85a70701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('survey_data',
               existing_type=mysql.JSON(),
               type_=sa.String(length=2048),
               existing_nullable=True)
        batch_op.alter_column('progression_data',
               existing_type=mysql.JSON(),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('progression_data',
               existing_type=sa.String(length=2048),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('survey_data',
               existing_type=sa.String(length=2048),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
