name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  deploy:
    name: Deploy to AWS EC2 via SSH
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            git config --global --add safe.directory /home/${{ secrets.EC2_USER }}/flask-backend-hospital
            cd /home/${{ secrets.EC2_USER }}/flask-backend-hospital
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
